name: antio_books
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  provider: ^6.1.5+1
  win32: ^5.15.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
