name: book_stack
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  book_stack_design_system:
    #path: ../book_stack_design_system
    git:
      url: https://github.com/jlamilla/book_stack_design_system
      ref: main
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.4
  http: ^1.5.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqlite3: ^2.9.3
  sqlite3_flutter_libs: ^0.5.15
  url_launcher: ^6.3.2
  win32: ^5.15.0

dev_dependencies:
  args: ^2.4.2
  build_runner: ^2.4.6
  custom_lint: ^0.8.0
  drift_dev: ^2.13.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  riverpod_lint: ^3.0.0-dev.4

dependency_overrides:
  build_runner: ^2.4.6
  args: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/bs.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icons/bs.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#168CFF"
  android_12:
    color: "#168CFF"
    branding: assets/icons/branding.png # opcional, puedes omitir si no tienes
    icon_background_color: "#168CFF"
  color_dark: "#168CFF"
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
